# Generated by Django 3.1.3 on 2020-11-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='binary_representation',
            field=models.JSONField(default=list),
        ),
    ]
