# Generated by Django 3.1.3 on 2020-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0006_auto_20201126_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='token',
            field=models.JSONField(default=list),
        ),
    ]
