# Generated by Django 3.1.3 on 2020-11-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0008_auto_20201126_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='token',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together=set(),
        ),
    ]
