# Generated by Django 3.1.3 on 2020-11-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0011_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sentence_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
