# Generated by Django 3.1.3 on 2020-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0012_document_sentence_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sentence_count',
            field=models.IntegerField(default=0),
        ),
    ]
